//! `aegist learn`: collect code to train on - from a folder, a git
//! repository, or a ready-made pack of well-known open-source projects.
//!
//! Files are filtered the way a careful person would: only source code,
//! nothing git ignores, no generated or minified files, no exact
//! duplicates. What's kept is copied to data/corpus/<source>/, and every
//! name used in it goes into data/names/<source>.txt - the list Aegist
//! checks its own code against, so it can tell when it has made a name up.

use crate::config::Settings;
use crate::corpus::{self, clean_code};
use crate::lang;
use crate::util::fnv1a;
use anyhow::{bail, Context, Result};
use std::collections::{BTreeSet, HashSet};
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Default)]
pub struct Learned {
    pub source: String,
    pub files: usize,
    pub bytes: u64,
    pub skipped: usize,
    pub duplicates: usize,
    pub names: usize,
}

/// Folders that hold dependencies, builds or caches, never skipped by
/// accident even when a project forgot to git-ignore them.
const SKIP_DIRS: &[&str] = &[
    "node_modules", "vendor", "target", "dist", "build", "out", ".git", "__pycache__", ".venv", "venv", "env", ".tox", ".mypy_cache",
    ".pytest_cache", ".next", ".nuxt", "coverage", "bower_components", ".gradle", ".idea", ".vscode", "third_party", "site-packages",
];

/// Why a file isn't worth training on, if it isn't.
pub fn reject_reason(path: &Path, bytes: &[u8], settings: &Settings) -> Option<&'static str> {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if !lang::is_code(path) {
        return Some("not source code");
    }
    if name.contains(".min.") || name.ends_with(".lock") || name.ends_with("-lock.json") || name == "package-lock.json" || name.ends_with(".map") {
        return Some("generated");
    }
    if bytes.len() as u64 > settings.code.max_file_kb * 1024 {
        return Some("too big");
    }
    if bytes.contains(&0) {
        return Some("binary");
    }
    if name.ends_with(".json") && bytes.len() > 64 * 1024 {
        return Some("data");
    }
    let text = String::from_utf8_lossy(bytes);
    if text.lines().any(|l| l.len() > settings.code.max_line_chars) {
        return Some("minified");
    }
    let head: String = text.chars().take(600).collect::<String>().to_lowercase();
    if head.contains("do not edit") || head.contains("autogenerated") || head.contains("auto-generated") || head.contains("@generated") {
        return Some("generated");
    }
    if text.trim().is_empty() {
        return Some("empty");
    }
    None
}

/// Every candidate source file under `root`, as git would see them.
pub fn source_files(root: &Path) -> Vec<PathBuf> {
    if root.is_file() {
        return vec![root.to_path_buf()];
    }
    let mut files: Vec<PathBuf> = ignore::WalkBuilder::new(root)
        .hidden(true)
        .git_ignore(true)
        .git_global(false)
        .require_git(false)
        .filter_entry(|e| !(e.file_type().is_some_and(|t| t.is_dir()) && SKIP_DIRS.contains(&e.file_name().to_str().unwrap_or(""))))
        .build()
        .flatten()
        .filter(|e| e.file_type().is_some_and(|t| t.is_file()))
        .map(|e| e.into_path())
        .filter(|p| lang::is_code(p))
        .collect();
    files.sort();
    files
}

/// A folder name that's safe on every system.
pub fn source_name(raw: &str) -> String {
    let base = raw.trim_end_matches(['/', '\\']).trim_end_matches(".git");
    let base = base.rsplit(['/', '\\', ':']).next().unwrap_or(base);
    let clean: String = base.chars().map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' { c } else { '-' }).collect();
    let clean = clean.trim_matches(['-', '.']).to_string();
    if clean.is_empty() { "code".into() } else { clean }
}

fn names_dir(settings: &Settings) -> PathBuf {
    settings.data_path("names")
}

/// Hashes of every file already in the corpus, to skip exact duplicates.
fn corpus_hashes(settings: &Settings, except: &Path) -> HashSet<u64> {
    corpus::corpus_files(settings)
        .into_iter()
        .filter(|f| !f.starts_with(except))
        .filter_map(|f| std::fs::read(f).ok())
        .map(|b| fnv1a(clean_code(&b).as_bytes()))
        .collect()
}

/// Copy the code in `root` (a folder or file) into the corpus as `source`,
/// replacing what an earlier `learn` of the same source put there.
pub fn learn_path(settings: &Settings, root: &Path, source: Option<&str>, log: &mut dyn FnMut(String)) -> Result<Learned> {
    if !root.exists() {
        bail!("{} doesn't exist", root.display());
    }
    let root = root.canonicalize()?;
    let source = source.map(source_name).unwrap_or_else(|| source_name(&root.to_string_lossy()));
    let dest = corpus::corpus_dir(settings).join(&source);
    let seen = corpus_hashes(settings, &dest);
    if dest.exists() {
        std::fs::remove_dir_all(&dest).with_context(|| format!("clearing {}", dest.display()))?;
    }
    let files = source_files(&root);
    log(format!("Reading {} source files in {}...", files.len(), root.display()));
    let mut report = Learned { source: source.clone(), ..Default::default() };
    let mut hashes: HashSet<u64> = HashSet::new();
    let mut names: BTreeSet<String> = BTreeSet::new();
    for f in &files {
        let Ok(bytes) = std::fs::read(f) else { continue };
        if reject_reason(f, &bytes, settings).is_some() {
            report.skipped += 1;
            continue;
        }
        let code = clean_code(&bytes);
        let h = fnv1a(code.as_bytes());
        if seen.contains(&h) || !hashes.insert(h) {
            report.duplicates += 1;
            continue;
        }
        let rel = if root.is_file() { PathBuf::from(f.file_name().unwrap_or_default()) } else { f.strip_prefix(&root).unwrap_or(f).to_path_buf() };
        let to = dest.join(&rel);
        if let Some(parent) = to.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&to, code.as_bytes())?;
        names.extend(lang::identifiers(&code).filter(|w| w.len() >= 2).map(str::to_string));
        report.files += 1;
        report.bytes += code.len() as u64;
    }
    report.names = names.len();
    let list: String = names.into_iter().map(|n| n + "\n").collect();
    std::fs::write(names_dir(settings).join(format!("{source}.txt")), list)?;
    Ok(report)
}

/// Clone a git repository (shallow) into data/sources/ and learn from it.
pub fn learn_git(settings: &Settings, url: &str, log: &mut dyn FnMut(String)) -> Result<Learned> {
    let name = source_name(url);
    let dir = settings.data_path("sources").join(&name);
    if dir.join(".git").is_dir() {
        log(format!("Updating {name}..."));
        let mut cmd = Command::new("git");
        cmd.arg("-C").arg(&dir).args(["pull", "--quiet", "--depth", "1"]);
        let ok = crate::proc::run(cmd, Some(std::time::Duration::from_secs(600)), None).is_ok_and(|o| o.ok());
        if !ok {
            log(format!("Couldn't update {name}; using the copy already downloaded."));
        }
    } else {
        log(format!("Downloading {url}..."));
        if dir.exists() {
            std::fs::remove_dir_all(&dir)?;
        }
        if crate::proc::which("git").is_none() {
            bail!("downloading needs git - install it from https://git-scm.com");
        }
        let mut cmd = Command::new("git");
        cmd.args(["clone", "--depth", "1", "--single-branch", "--quiet", url]).arg(&dir);
        let out = crate::proc::run(cmd, Some(std::time::Duration::from_secs(1800)), None).context("couldn't run git")?;
        if !out.ok() {
            let why = out.combined();
            bail!("git couldn't download {url}: {}", why.lines().last().unwrap_or("no reason given"));
        }
    }
    learn_path(settings, &dir, Some(&name), log)
}

/// A source argument: a git URL, or a folder/file.
pub fn is_git_url(s: &str) -> bool {
    s.starts_with("https://") || s.starts_with("http://") || s.starts_with("git@") || s.starts_with("ssh://") || s.ends_with(".git")
}

pub struct Pack {
    pub name: &'static str,
    pub about: &'static str,
    pub repos: &'static [&'static str],
}

/// Ready-made sets of well-known, openly licensed projects. Each is
/// downloaded with git straight from its own repository; nothing here is
/// another AI - it's code people wrote, for Aegist to read.
pub const PACKS: &[Pack] = &[
    Pack { name: "python", about: "Python libraries, tools and algorithms", repos: &[
        "https://github.com/TheAlgorithms/Python", "https://github.com/psf/requests", "https://github.com/pallets/flask",
        "https://github.com/pallets/click", "https://github.com/psf/black", "https://github.com/fastapi/fastapi",
        "https://github.com/pytest-dev/pytest", "https://github.com/httpie/cli"] },
    Pack { name: "javascript", about: "JavaScript on the web and in Node", repos: &[
        "https://github.com/TheAlgorithms/JavaScript", "https://github.com/expressjs/express", "https://github.com/lodash/lodash",
        "https://github.com/axios/axios", "https://github.com/jquery/jquery", "https://github.com/chartjs/Chart.js"] },
    Pack { name: "typescript", about: "TypeScript libraries and tools", repos: &[
        "https://github.com/TheAlgorithms/TypeScript", "https://github.com/colinhacks/zod", "https://github.com/vitejs/vite",
        "https://github.com/vuejs/core"] },
    Pack { name: "web", about: "Websites: HTML, CSS and front-end JavaScript", repos: &[
        "https://github.com/mdn/learning-area", "https://github.com/twbs/bootstrap", "https://github.com/sveltejs/svelte",
        "https://github.com/jquery/jquery"] },
    Pack { name: "games", about: "Games in JavaScript, Python and C", repos: &[
        "https://github.com/gabrielecirulli/2048", "https://github.com/ellisonleao/clumsy-bird", "https://github.com/pygame/pygame",
        "https://github.com/kitao/pyxel", "https://github.com/raysan5/raylib"] },
    Pack { name: "rust", about: "Rust applications and libraries", repos: &[
        "https://github.com/TheAlgorithms/Rust", "https://github.com/BurntSushi/ripgrep", "https://github.com/serde-rs/serde",
        "https://github.com/clap-rs/clap", "https://github.com/tokio-rs/tokio"] },
    Pack { name: "go", about: "Go services and command-line tools", repos: &[
        "https://github.com/TheAlgorithms/Go", "https://github.com/gin-gonic/gin", "https://github.com/spf13/cobra",
        "https://github.com/junegunn/fzf"] },
    Pack { name: "c", about: "C: systems code, servers and small classics", repos: &[
        "https://github.com/TheAlgorithms/C", "https://github.com/antirez/kilo", "https://github.com/redis/redis",
        "https://github.com/curl/curl"] },
    Pack { name: "cpp", about: "C++ libraries", repos: &[
        "https://github.com/TheAlgorithms/C-Plus-Plus", "https://github.com/nlohmann/json", "https://github.com/fmtlib/fmt",
        "https://github.com/ocornut/imgui"] },
    Pack { name: "java", about: "Java", repos: &["https://github.com/TheAlgorithms/Java", "https://github.com/google/gson"] },
    Pack { name: "os", about: "Operating systems: kernels, boot code, drivers", repos: &[
        "https://github.com/mit-pdos/xv6-riscv", "https://github.com/mit-pdos/xv6-public", "https://github.com/cfenollosa/os-tutorial",
        "https://github.com/jdah/tetris-os", "https://github.com/klange/toaruos"] },
    Pack { name: "ai", about: "Neural networks and language models, written from scratch", repos: &[
        "https://github.com/karpathy/micrograd", "https://github.com/karpathy/nanoGPT", "https://github.com/karpathy/minGPT",
        "https://github.com/karpathy/makemore", "https://github.com/karpathy/llama2.c", "https://github.com/karpathy/llm.c"] },
    Pack { name: "algorithms", about: "Classic algorithms in many languages", repos: &[
        "https://github.com/TheAlgorithms/Python", "https://github.com/TheAlgorithms/JavaScript", "https://github.com/TheAlgorithms/Rust",
        "https://github.com/TheAlgorithms/Go", "https://github.com/TheAlgorithms/C", "https://github.com/TheAlgorithms/C-Plus-Plus",
        "https://github.com/TheAlgorithms/Java", "https://github.com/TheAlgorithms/TypeScript"] },
];

pub fn pack(name: &str) -> Option<&'static Pack> {
    PACKS.iter().find(|p| p.name.eq_ignore_ascii_case(name))
}

/// What's in the corpus: (source, files, bytes), biggest first.
pub fn sources(settings: &Settings) -> Vec<(String, usize, u64)> {
    let root = corpus::corpus_dir(settings);
    let mut out: Vec<(String, usize, u64)> = Vec::new();
    for f in corpus::corpus_files(settings) {
        let rel = f.strip_prefix(&root).unwrap_or(&f).to_string_lossy().replace('\\', "/");
        let src = rel.split('/').next().unwrap_or("").to_string();
        let size = std::fs::metadata(&f).map(|m| m.len()).unwrap_or(0);
        match out.iter_mut().find(|s| s.0 == src) {
            Some(s) => {
                s.1 += 1;
                s.2 += size;
            }
            None => out.push((src, 1, size)),
        }
    }
    out.sort_by(|a, b| b.2.cmp(&a.2));
    out
}

/// Forget a source: its code and its names.
pub fn forget(settings: &Settings, source: &str) -> Result<bool> {
    let dir = corpus::corpus_dir(settings).join(source_name(source));
    let names = names_dir(settings).join(format!("{}.txt", source_name(source)));
    let existed = dir.exists();
    if existed {
        std::fs::remove_dir_all(&dir)?;
    }
    let _ = std::fs::remove_file(names);
    Ok(existed)
}

/// Every name that appears anywhere in the code Aegist learned from.
pub fn known_names(settings: &Settings) -> HashSet<String> {
    let mut all = HashSet::new();
    if let Ok(entries) = std::fs::read_dir(names_dir(settings)) {
        for e in entries.flatten() {
            if let Ok(text) = std::fs::read_to_string(e.path()) {
                all.extend(text.lines().map(str::to_string));
            }
        }
    }
    all
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::testing;

    #[test]
    fn learns_only_real_source_code_once() {
        let tmp = tempfile::tempdir().unwrap();
        let s = testing::settings(&tmp.path().join("data"));
        let src = tmp.path().join("My Project");
        for (path, text) in [
            ("main.py", "def greet(name):\n    return 'hi ' + name\n"),
            ("copy.py", "def greet(name):\n    return 'hi ' + name\n"),
            ("lib/util.rs", "pub fn twice(x: i32) -> i32 { x * 2 }\n"),
            ("notes.txt", "not code"),
            ("app.min.js", "var a=1;"),
            ("node_modules/dep/index.js", "module.exports = 1;\n"),
            ("gen.py", "# Code generated by a tool. DO NOT EDIT.\nx = 1\n"),
            ("ignored/skip.py", "x = 2\n"),
        ] {
            let p = src.join(path);
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, text).unwrap();
        }
        std::fs::write(src.join(".gitignore"), "ignored/\n").unwrap();
        let r = learn_path(&s, &src, None, &mut |_| {}).unwrap();
        assert_eq!(r.source, "My-Project");
        assert_eq!((r.files, r.duplicates), (2, 1), "{r:?}");
        let learned = sources(&s);
        assert_eq!(learned.len(), 1);
        assert_eq!(learned[0].1, 2);
        let names = known_names(&s);
        assert!(names.contains("greet") && names.contains("twice") && !names.contains("exports"));
        // learning again replaces, not duplicates
        assert_eq!(learn_path(&s, &src, None, &mut |_| {}).unwrap().files, 2);
        assert!(forget(&s, "My-Project").unwrap());
        assert!(sources(&s).is_empty() && known_names(&s).is_empty());
    }

    #[test]
    fn names_and_urls() {
        assert_eq!(source_name("https://github.com/psf/requests.git"), "requests");
        assert_eq!(source_name("/home/me/code/my app/"), "my-app");
        assert!(is_git_url("https://github.com/a/b") && is_git_url("git@github.com:a/b.git") && !is_git_url("./src"));
        assert!(pack("Python").is_some() && pack("cobol").is_none());
        assert!(PACKS.iter().all(|p| p.repos.iter().all(|r| r.starts_with("https://github.com/"))));
    }
}
